CREATE DATABASE Senatur_Manha
GO

USE Senatur_Manha;
GO

CREATE TABLE TiposUsuario
(
	IdTipoUsuario INT IDENTITY PRIMARY KEY,
	Titulo VARCHAR (50) UNIQUE NOT NULL ,
);
GO

CREATE TABLE Usuarios
(
	IdUsuario INT IDENTITY PRIMARY KEY,
	Email VARCHAR (100) UNIQUE NOT NULL,
	Senha VARCHAR (20) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario)
);
GO

CREATE TABLE Pacotes
(
	IdPacote INT IDENTITY PRIMARY KEY ,
	NomePacote VARCHAR (150) NOT NULL,
	Descricao TEXT NOT NULL,
	DataIda DATETIME NOT NULL,
	DataVolta DATETIME NOT NULL,
	Valor DECIMAL (18,2) NOT NULL,
	Ativo BIT DEFAULT (1) NOT NULL,
	Cidade VARCHAR (100) NOT NULL
);
GO
